import json
import networkx as nx
from pathlib import Path
from typing import Dict, List, Any, Tuple
from datetime import datetime
from src.graph.knowledge_graph import KnowledgeGraph
from src.models.schemas import TraceEvent, ModuleNode
from src.analyzers.git_history import GitVelocitySnapshot

class ArchivistAgent:
    """
    Master-Tier Archivist: Produces high-density, AI-ready artifacts.
    
    Responsibilities:
    - Generate CODEBASE.md with complete system context for AI agents
    - Ensure artifact persistence (Definition of Done)
    - Synthesize outputs from Surveyor, Hydrologist, and Semanticist
    - Maintain audit trail with confidence levels
    """
    
    def __init__(self, kg: KnowledgeGraph | None = None, root_path: str = "."):
        self.kg = kg or KnowledgeGraph()
        self.root_path = Path(root_path)
        self.output_dir = self.root_path / ".cartography"
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.required_artifacts = [
            "knowledge_graph.json",
            "semantic_index.json",
            "CODEBASE.md",
            "onboarding_brief.md",
            "cartography_trace.jsonl",
        ]

    def write_module_graph(self, kg: KnowledgeGraph) -> Path:
        dest = self.output_dir / "module_graph.json"
        kg.save(dest)
        return dest

    def write_lineage_graph(self, kg: KnowledgeGraph) -> Path:
        dest = self.output_dir / "lineage_graph.json"
        kg.save(dest)
        return dest

    def write_semantic_index(self, modules: dict[str, ModuleNode]) -> Path:
        dest = self.output_dir / "semantic_index.json"
        data = {path: mod.model_dump(mode="json") for path, mod in modules.items()}
        dest.write_text(json.dumps(data, indent=2))
        return dest

    def write_trace(self, trace: list[TraceEvent]) -> Path:
        """Write trace as JSONL for streaming/append operations."""
        dest = self.output_dir / "cartography_trace.jsonl"
        with dest.open("w") as f:
            for event in trace:
                event_data = event.model_dump(mode="json")
                # Add timestamp and method classification
                event_data["timestamp"] = datetime.now().isoformat()
                event_data["method"] = "Static" if event.agent in ["surveyor", "hydrologist"] else "LLM"
                f.write(json.dumps(event_data) + "\n")
        return dest

    def generate_codebase_md(
        self,
        modules: dict[str, ModuleNode],
        kg: KnowledgeGraph,
        pagerank_scores: dict[str, float],
        scc: list[list[str]],
        sources: list[str],
        sinks: list[str],
        git_velocity_snapshot: GitVelocitySnapshot | None = None,
        git_velocity_days: int = 90
    ) -> Path:
        """
        Generates HIGH-DENSITY CODEBASE.md for AI agent injection.
        
        Sections:
        1. Architecture Overview (domain clusters + topology)
        2. Critical Path (Top 10 PageRank modules)
        3. Data Inventory (Sources & Sinks)
        4. System Vital Signs (metrics)
        5. Known Debt & Risk (high velocity + dead code)
        6. Module Purpose Index (complete table)
        """
        project_name = self.root_path.name
        
        # Header
        content = f"# CODEBASE.md: {project_name}\n\n"
        content += "**AI-Ready System Context** | Generated by Legacy Code Cartographer\n\n"
        content += f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        content += "---\n\n"
        
        # 1. ARCHITECTURE OVERVIEW
        content += "## 🏗️ Architecture Overview\n\n"
        domain_clusters = self._extract_domain_clusters(modules)
        if domain_clusters:
            content += "**Domain Clusters:**\n\n"
            for domain, count in sorted(domain_clusters.items(), key=lambda x: x[1], reverse=True)[:10]:
                content += f"- **{domain}**: {count} modules\n"
        else:
            content += "*Domain clustering not available*\n"
        
        content += f"\n**Graph Topology:**\n"
        content += f"- Total Nodes: {kg.graph.number_of_nodes()}\n"
        content += f"- Total Edges: {kg.graph.number_of_edges()}\n"
        content += f"- Density: {nx.density(kg.graph):.4f}\n"
        content += f"- Strongly Connected Components: {len(list(nx.strongly_connected_components(kg.graph)))}\n\n"
        
        # 2. CRITICAL PATH (Top 10 Load-Bearing Modules)
        content += "## 🎯 The Critical Path (Load-Bearing Modules)\n\n"
        content += "**Top 10 modules by PageRank centrality** (highest impact on system):\n\n"
        content += "| Rank | Module | PageRank | In-Degree | Out-Degree | Purpose |\n"
        content += "|------|--------|----------|-----------|------------|---------|\n"
        
        top_10 = sorted(pagerank_scores.items(), key=lambda x: x[1], reverse=True)[:10]
        for rank, (node_id, score) in enumerate(top_10, 1):
            in_deg = kg.graph.in_degree(node_id)
            out_deg = kg.graph.out_degree(node_id)
            attrs = kg.graph.nodes.get(node_id, {})
            purpose = attrs.get("purpose_statement", "Analysis Pending")[:60]
            if len(attrs.get("purpose_statement", "")) > 60:
                purpose += "..."
            content += f"| {rank} | `{node_id}` | {score:.5f} | {in_deg} | {out_deg} | {purpose} |\n"
        
        content += "\n"
        
        # 3. DATA INVENTORY (Sources & Sinks)
        content += "## 🚰 Data Inventory\n\n"
        content += "### Data Sources (Ingestion Points)\n\n"
        if sources:
            content += f"**{len(sources)} source nodes identified** (In-Degree = 0 or explicit SourceNode tags):\n\n"
            for src in sources[:15]:
                attrs = kg.graph.nodes.get(src, {})
                node_type = attrs.get("node_type", "unknown")
                content += f"- `{src}` ({node_type})\n"
            if len(sources) > 15:
                content += f"\n*...and {len(sources) - 15} more sources*\n"
        else:
            content += "*No explicit sources detected*\n"
        
        content += "\n### Data Sinks (Output Points)\n\n"
        if sinks:
            content += f"**{len(sinks)} sink nodes identified** (Out-Degree = 0 or explicit SinkNode tags):\n\n"
            for sink in sinks[:15]:
                attrs = kg.graph.nodes.get(sink, {})
                node_type = attrs.get("node_type", "unknown")
                storage = attrs.get("storage_type", "")
                if storage:
                    content += f"- `{sink}` ({node_type}, {storage})\n"
                else:
                    content += f"- `{sink}` ({node_type})\n"
            if len(sinks) > 15:
                content += f"\n*...and {len(sinks) - 15} more sinks*\n"
        else:
            content += "*No explicit sinks detected*\n"
        
        content += "\n"
        
        # 4. SYSTEM VITAL SIGNS
        content += "## 📊 System Vital Signs\n\n"
        total_modules = len(modules)  # All items in modules dict are ModuleNode instances
        total_lineage = kg.graph.number_of_edges()
        avg_complexity = sum(m.complexity_score for m in modules.values() if m.complexity_score) / max(len(modules), 1)
        
        content += f"- **Total Module Nodes:** {total_modules}\n"
        content += f"- **Total Lineage Relations:** {total_lineage}\n"
        content += f"- **Average Cyclomatic Complexity:** {avg_complexity:.2f}\n"
        
        if git_velocity_snapshot:
            content += f"- **Git Velocity Window:** {git_velocity_days} days\n"
            content += f"- **Files with Recent Changes:** {len(git_velocity_snapshot.files)}\n"
            content += f"- **History Status:** {git_velocity_snapshot.history_status}\n"
        
        content += "\n"
        
        # 5. KNOWN DEBT & RISK
        content += "## ⚠️ Known Debt & Risk\n\n"
        
        # High velocity modules (change frequently)
        high_velocity = [
            (path, m) for path, m in modules.items()
            if m.change_velocity_30d and m.change_velocity_30d > 5
        ]
        high_velocity.sort(key=lambda x: x[1].change_velocity_30d, reverse=True)
        
        content += "### High-Velocity Modules (Frequent Changes)\n\n"
        if high_velocity:
            content += "**Modules with >5 commits in last 30 days:**\n\n"
            content += "| Module | Velocity (30d) | Complexity | Risk Level |\n"
            content += "|--------|----------------|------------|------------|\n"
            for path, mod in high_velocity[:10]:
                risk = "🔴 HIGH" if mod.complexity_score > 50 else "🟡 MEDIUM"
                content += f"| `{path}` | {mod.change_velocity_30d} | {mod.complexity_score:.1f} | {risk} |\n"
        else:
            content += "*No high-velocity modules detected*\n"
        
        content += "\n### Dead Code Candidates\n\n"
        dead_code = [path for path, m in modules.items() if m.is_dead_code_candidate]
        if dead_code:
            content += f"**{len(dead_code)} modules flagged as potential dead code:**\n\n"
            for path in dead_code[:15]:
                content += f"- `{path}`\n"
            if len(dead_code) > 15:
                content += f"\n*...and {len(dead_code) - 15} more candidates*\n"
        else:
            content += "*No dead code candidates detected*\n"
        
        content += "\n### Circular Dependencies\n\n"
        cycles = [c for c in scc if len(c) > 1]
        if cycles:
            content += f"**{len(cycles)} circular dependency clusters detected:**\n\n"
            for i, cycle in enumerate(cycles[:5], 1):
                cycle_str = " → ".join(cycle[:4])
                if len(cycle) > 4:
                    cycle_str += " → ..."
                content += f"{i}. {cycle_str}\n"
            if len(cycles) > 5:
                content += f"\n*...and {len(cycles) - 5} more cycles*\n"
        else:
            content += "✅ No circular dependencies detected\n"
        
        content += "\n"
        
        # 6. MODULE PURPOSE INDEX
        content += "## � Module Purpose Index\n\n"
        content += "**Complete mapping of file paths to LLM-derived purpose statements:**\n\n"
        content += "| File Path | Purpose Statement | Complexity | Language |\n"
        content += "|-----------|-------------------|------------|----------|\n"
        
        sorted_modules = sorted(modules.items(), key=lambda x: x[0])
        for path, mod in sorted_modules:
            # All items in modules dict are ModuleNode instances
            purpose = mod.purpose_statement or "Analysis Pending"
            # Truncate long purposes
            if len(purpose) > 80:
                purpose = purpose[:77] + "..."
            complexity = f"{mod.complexity_score:.1f}" if mod.complexity_score else "N/A"
            lang = mod.language or "unknown"
            content += f"| `{path}` | {purpose} | {complexity} | {lang} |\n"
        
        content += "\n---\n\n"
        content += "**End of CODEBASE.md** | Use this document to understand system architecture, identify critical paths, and assess technical debt.\n"
        
        output_path = self.output_dir / "CODEBASE.md"
        output_path.write_text(content)
        return output_path
    
    def _extract_domain_clusters(self, modules: dict[str, ModuleNode]) -> dict[str, int]:
        """Extract domain clusters from module metadata."""
        clusters = {}
        for mod in modules.values():
            domain = mod.domain_cluster or "uncategorized"
            clusters[domain] = clusters.get(domain, 0) + 1
        return clusters

    def generate_onboarding_brief(self, day_one_answers: str) -> Path:
        """Generates the FDE Day-One Brief with citations."""
        output_path = self.output_dir / "onboarding_brief.md"
        
        # Add header
        content = "# Onboarding Brief: First Day Engineering Questions\n\n"
        content += f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        content += "This brief answers the 5 critical questions every engineer asks on Day One.\n\n"
        content += "---\n\n"
        content += day_one_answers
        
        output_path.write_text(content)
        return output_path
    
    def verify_artifact_completeness(self) -> Tuple[bool, List[str]]:
        """
        Verify all required artifacts exist (Definition of Done).
        
        Returns:
            (is_complete, missing_artifacts)
        """
        missing = []
        for artifact in self.required_artifacts:
            artifact_path = self.output_dir / artifact
            if not artifact_path.exists():
                missing.append(artifact)
        
        return (len(missing) == 0, missing)

if __name__ == "__main__":
    from src.graph.knowledge_graph import KnowledgeGraph
    kg = KnowledgeGraph()
    archivist = ArchivistAgent(kg, "targets/meltano")
    archivist.generate_CODEBASE_md(["meltano.core.project", "meltano.core.plugin_invoker"])
